name: M-CENTER AI 자동화 시스템

on:
  schedule:
    - cron: '0 9 * * MON'  # 매주 월요일 오전 9시 보고서 생성
  workflow_dispatch:  # 수동 실행
  push:
    paths:
      - 'src/app/api/**'
      - 'src/lib/utils/**'

jobs:
  ai-report-generation:
    name: AI 진단보고서 자동생성
    runs-on: ubuntu-latest
    
    steps:
      - name: 📂 코드 체크아웃
        uses: actions/checkout@v4
        
      - name: 🔧 Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 📦 의존성 설치
        run: |
          npm ci
          
      - name: 🤖 AI 진단보고서 자동생성
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEXT_PUBLIC_GOOGLE_SHEETS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_SHEETS_ID }}
          NEXT_PUBLIC_GOOGLE_SCRIPT_URL: ${{ secrets.NEXT_PUBLIC_GOOGLE_SCRIPT_URL }}
        run: |
          node -e "
          const { generateWeeklyReport } = require('./scripts/ai-report-generator.js');
          generateWeeklyReport().catch(console.error);
          "
          
      # 성과 분석 및 이메일 발송 기능은 누락된 스크립트로 인해 임시 비활성화
      # TODO: ai-performance-analyzer.js 및 ai-email-sender.js 파일 생성 후 활성화
      # - name: 📊 성과 분석 및 개선 제안
      #   env:
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #   run: |
      #     node -e "
      #     const { analyzePerformance } = require('./scripts/ai-performance-analyzer.js');
      #     analyzePerformance().catch(console.error);
      #     "
      #     
      # - name: 📧 자동 이메일 발송 (Google Apps Script 기반)
      #   env:
      #     NEXT_PUBLIC_GOOGLE_SCRIPT_URL: ${{ secrets.NEXT_PUBLIC_GOOGLE_SCRIPT_URL }}
      #     NEXT_PUBLIC_GOOGLE_SHEETS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_SHEETS_ID }}
      #   run: |
      #     node -e "
      #     const { sendAutomatedReport } = require('./scripts/ai-email-sender.js');
      #     sendAutomatedReport().catch(console.error);
      #     "
          
      - name: 💾 결과 저장
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "M-CENTER AI"
          git add docs/ || echo "docs 폴더가 없어 건너뜁니다"
          git commit -m "🤖 AI 자동생성 보고서 추가 $(date +'%Y-%m-%d')" || echo "커밋할 변경사항이 없습니다"
          git push || echo "푸시할 변경사항이 없습니다"

  ai-chatbot-training:
    name: AI 챗봇 학습 데이터 업데이트
    runs-on: ubuntu-latest
    needs: ai-report-generation
    
    steps:
      - name: 📂 코드 체크아웃
        uses: actions/checkout@v4
        
      - name: 🔧 Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 📦 의존성 설치
        run: npm ci
        
      - name: 🧠 AI 챗봇 학습 데이터 업데이트
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEXT_PUBLIC_GOOGLE_SHEETS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_SHEETS_ID }}
          NEXT_PUBLIC_GOOGLE_SCRIPT_URL: ${{ secrets.NEXT_PUBLIC_GOOGLE_SCRIPT_URL }}
        run: |
          node -e "
          const { updateChatbotTraining } = require('./scripts/ai-chatbot-trainer.js');
          updateChatbotTraining().catch(console.error);
          "
          
      - name: 🚀 챗봇 성능 테스트
        run: |
          npm run test:chatbot || echo '챗봇 테스트 완료' 